### ISSUE TITLE
Small typo -> "Brienne of Tharth", s/b "Brienne of Tarth",

### ISSUE THREAD

**Issue by Ewa-Anna** [shevabam/game-of-thrones-quotes-api#10]
Hi! I hope you don't mind me opening an issue, but I didn't want to create pull request for just one letter :slightly_smiling_face:
I've noticed that in the datas.json file there is small typo in the name of Brienne. 
The house is correct, but the name contains extra letter 'h'.
Source: https://en.wikipedia.org/wiki/Brienne_of_Tarth

![image](https://github.com/shevabam/game-of-thrones-quotes-api/assets/99288124/95522ed6-8d40-4b8d-bd4f-c8c806bd2fbf)

Link to code: [https://github.com/shevabam/game-of-thrones-quotes-api/blob/master/datas.json](https://github.com/shevabam/game-of-thrones-quotes-api/blob/master/datas.json)
Line 112

**Comment by shevabam** [comment]
Hi! Thanks, it's fixed ;)
